[package]
name = "chess_computer"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_egui = "0.21.0"
dyn-clone = "1.0"
strum = "0.25"
strum_macros = "0.25"

[dependencies.bevy]
version = "0.11"
features = ["default", "wav"]
