name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
    contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Build docs
        run: cargo doc --all-features --no-deps

      - name: Install wasm
        run: rustup target add wasm32-unknown-unknown

      - name: Install trunk
        run: cargo install --locked trunk; cargo install --locked wasm-bindgen-cli

      - name: Build trunk
        run: trunk build --release

      #  This adds the following:
      #   - A top level redirect to the bevy crate documentation
      #   - A robots.txt file to forbid any crawling of the site (to defer to the docs.rs site on search engines).
      #   - A .nojekyll file to disable Jekyll GitHub Pages builds.
      # - name: Finalize documentation
      #   run: |
      #     echo "<meta http-equiv=\"refresh\" content=\"0; url=chess_computer/index.html\">" > target/doc/index.html
      #     echo "User-Agent: *\nDisallow: /" > target/doc/robots.txt
      #     touch target/doc/.nojekyll


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
